### ISSUE TITLE
Erro ao clicar no logo DeCS/MeSH Finder da URL https://decsfinder.bvsalud.org/dmfw

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/DeCSMeSHHighlighter#11]
![image](https://user-images.githubusercontent.com/1226218/106474952-2f7b4300-6484-11eb-86f0-4f66f0851721.png)

O logo está indo para https://decsfinder.bvsalud.org/dmhs ao invés de https://decsfinder.bvsalud.org/dmfs

**Comment by heitorbarbieri** [comment]
Corrigido no commit ed949cc
