### ISSUE TITLE
Avaliar queda no número de acessos ao DeCS Finder

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/DeCSMeSHHighlighter#21]
![image](https://user-images.githubusercontent.com/1226218/138987491-6ed905ed-8f54-4fa3-9ef4-842199e520da.png)

**Comment by heitorbarbieri** [comment]
Ação sugerida acima realizada. Aparentemente produziu algum efeito positivo.

![Captura de tela de 2022-03-30 16-52-32](https://user-images.githubusercontent.com/2152778/160919821-b6398d0e-8827-4bf9-a749-82e7f5894ada.png)
