### ISSUE TITLE
Inserir código para ativação do Google Analytics nas páginas html

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/DeCSMeSHHighlighter#3]

**Comment by heitorbarbieri** [comment]
Feito no commit # c6ee257. @renatomurasaki , por favor, validar se o funcionamento nas páginas do Google Analytics está correto. Obrigado.

**Comment by heitorbarbieri** [comment]
@renatomurasaki percebi no Google Analytics que ao clicar no botão assinalado na figura abaixo, que ele tenta abrir a url "https://dmhighlighter.bvsalud.org/decsmeshhighlighter/dmhw" quando na verdade a url correta é "https://dmhighlighter.bvsalud.org/dmhw". Você tem alguma sugestão de solução?

![Captura de tela de 2020-09-16 11-13-22](https://user-images.githubusercontent.com/2152778/93350082-a0d89300-f80e-11ea-98cf-884b5d028141.png)

**Comment by renatomurasaki** [comment]
> Feito no commit # [c6ee257](https://github.com/bireme/DeCSMeSHHighlighter/commit/c6ee257cbed721c45a1127c34d247af76ca5b745). @renatomurasaki , por favor, validar se o funcionamento nas páginas do Google Analytics está correto. Obrigado.

@heitorbarbieri parece estar registrando corretamente no Google Analytics. Obrigado.

**Comment by renatomurasaki** [comment]
> @renatomurasaki percebi no Google Analytics que ao clicar no botão assinalado na figura abaixo, que ele tenta abrir a url "https://dmhighlighter.bvsalud.org/decsmeshhighlighter/dmhw" quando na verdade a url correta é "https://dmhighlighter.bvsalud.org/dmhw". Você tem alguma sugestão de solução?
> 
> ![Captura de tela de 2020-09-16 11-13-22](https://user-images.githubusercontent.com/2152778/93350082-a0d89300-f80e-11ea-98cf-884b5d028141.png)

Isso ocorre em outros sites também, porém não sei porque o GA assume incorretamente o diretório do site. De qq forma, não impacta a estatística, apenas dificulta o acesso direto à respectiva página

**Comment by heitorbarbieri** [comment]
Feito no commit c6ee257
