### ISSUE TITLE
Melhorar a usabilidade da FAQ na página inicial

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/DeCSMeSHHighlighter#8]
Creio que ajudaria se houvesse uma diferenciação da cor de fundo da pergunta e da resposta, ou que pelo menos a resposta estivesse com recuo para a direita, evitando-se o alinhamento com a pergunta.

**Comment by heitorbarbieri** [comment]
@marcioalvessilva você pode me ajudar?

**Comment by heitorbarbieri** [comment]
Feito no commit f7d32c8
